### ISSUE TITLE
Publishing to Azure Issues

### ISSUE THREAD

**Issue by dennyglee** [Azure-Samples/azure-cosmos-db-dotnet-graphexplorer#6]
This may very well be a newbie question so if it is, my sincere apologies.  I'm able to build the solution but once I deploy it (to azurewebsites.net), the page just has "Loading....".  Wondering if there is something I may be missing to be able to deploy this solution?  Thanks!

**Comment by sstchur** [comment]
Also, do be aware that if you publish an app to azurewebsite (or anywhere) then anyone with a browser can access it, and therefore can see the data in your CosmosDB.  Additionally, since the UI exposes the ability to create new collections, anyone with access to your URL can create collections in your DB, thus having a financial impact on your/your Azure subscription.

Another dev recently submitting a PR which was merged that supports AAD auth.  It might be a good idea to make sure of this if you are publishing your app to the wild.
